packages:
  - telemetry
  - scripts/skills-deploy
  - scripts/claude-ui-upload
  - packages/lint-changed
  - packages/prompt-injection-scanner

onlyBuiltDependencies:
  - esbuild
  - msw
  - unrs-resolver
