#!/usr/bin/env sh
NODE_OPTIONS="--experimental-strip-types" pnpx lint-staged --verbose
if git diff --cached --name-only | grep -q '^telemetry/'; then
  cd telemetry && NODE_OPTIONS=--experimental-strip-types pnpx lint-staged --verbose
fi
